grammar_app/urls.py
from django.urls import path
from .views import (
    CategoryDetailView, FormDetailView, SearchResultsView,
    UslubView, YordamchiSozView, UmumiyBazaView, HomeView, WordSynonymView,
    GrammatikManoView, DavriylikiView, SinonimlarView,
    about, export_category, import_yordamchi_excel,
    import_sinonimlar_excel, import_grammatik_excel, import_davriylik_excel
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),  # Home page
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('form/<int:pk>/', FormDetailView.as_view(), name='form_detail'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('about/', about, name='about'),
    path('export/<int:category_id>/<str:format>/', export_category, name='export_category'),
    path('yordamchi-soz/', YordamchiSozView.as_view(), name='yordamchi_soz'),
    path('yordamchi-soz/umumiy-baza/', UmumiyBazaView.as_view(), name='umumiy_baza'),
    path('yordamchi-soz/import/', import_yordamchi_excel, name='import_yordamchi'),
    path('yordamchi-soz/sinonimlar/', SinonimlarView.as_view(), name='sinonimlar'),
    path('yordamchi-soz/import-sinonimlar/', import_sinonimlar_excel, name='import_sinonimlar'),
    path('yordamchi-soz/uslub/', UslubView.as_view(), name='uslub'),
    path('yordamchi-soz/word-synonyms/', WordSynonymView.as_view(), name='word_synonyms'),
    path('yordamchi-soz/grammatik-mano/', GrammatikManoView.as_view(), name='grammatik_mano'),
    path('yordamchi-soz/import-grammatik/', import_grammatik_excel, name='import_grammatik'),
    path('yordamchi-soz/davriylik/', DavriylikiView.as_view(), name='davriylik'),
    path('yordamchi-soz/import-davriylik/', import_davriylik_excel, name='import_davriylik'),
]

uzbek_grammar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grammar_app.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

grammar_app/models.py
from django.db import models
from django.urls import reverse


class GrammaticalCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    order = models.IntegerField(default=0)  # For custom ordering

    class Meta:
        ordering = ['order', 'name']
        verbose_name_plural = "Grammatical Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'pk': self.pk})


class GrammaticalForm(models.Model):
    TURKUMI_CHOICES = [
        ('Ko\'makchi', 'Ko\'makchi'),
        ('Bog\'lovchi', 'Bog\'lovchi'),
        ('Yuklama', 'Yuklama'),
    ]

    category = models.ForeignKey(GrammaticalCategory, on_delete=models.CASCADE, related_name='forms')
    term = models.CharField(max_length=255)
    grammatical_meaning = models.TextField()
    usage = models.CharField(max_length=100, choices=TURKUMI_CHOICES, verbose_name='Turkumi')
    translation = models.TextField(blank=True)
    period = models.CharField(max_length=100, blank=True)
    style = models.CharField(max_length=100, blank=True)
    
    special_code = models.CharField(max_length=100, blank=True)
    style_literary = models.CharField(max_length=100, blank=True)
    style_scientific = models.CharField(max_length=100, blank=True)
    style_journalistic = models.CharField(max_length=100, blank=True)
    style_official = models.CharField(max_length=100, blank=True)
    style_colloquial = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ['term']

    def __str__(self):
        return f"{self.term} ({self.category.name})"

    def get_absolute_url(self):
        return reverse('form_detail', kwargs={'pk': self.pk})


class Example(models.Model):
    grammatical_form = models.ForeignKey(GrammaticalForm, on_delete=models.CASCADE, related_name='examples')
    uzbek_text = models.TextField()  # Using TextField for unlimited length
    english_translation = models.TextField(blank=True)  # Using TextField for unlimited length

    def __str__(self):
        return self.uzbek_text[:50]


class UslubData(models.Model):
    yordamchi_soz = models.CharField(max_length=255, verbose_name="Yordamchi so'z")
    maxsus_kodi = models.CharField(max_length=255, verbose_name="Maxsus kodi", blank=True)
    grammatik_manosi = models.TextField(verbose_name="Grammatik ma'nosi", blank=True)
    badiiy = models.BooleanField(default=False, verbose_name="Badiiy")
    ilmiy = models.BooleanField(default=False, verbose_name="Ilmiy")
    publitsistik = models.BooleanField(default=False, verbose_name="Publitsistik")
    rasmiy = models.BooleanField(default=False, verbose_name="Rasmiy")
    sozlashuv = models.BooleanField(default=False, verbose_name="So'zlashuv")

    def __str__(self):
        return self.yordamchi_soz

    class Meta:
        verbose_name = "Uslub ma'lumoti"
        verbose_name_plural = "Uslub ma'lumotlari"


class WordSynonym(models.Model):
    grammatical_word = models.CharField(max_length=255, verbose_name="Grammatik so'z")
    translations = models.TextField(verbose_name="Tarjimalar", blank=True)
    identity = models.CharField(max_length=255, verbose_name="Identifikator", blank=True)
    synonyms = models.TextField(verbose_name="Sinonimlar", blank=True)

    class Meta:
        verbose_name = "So'z sinonimi"
        verbose_name_plural = "So'z sinonimlari"
        ordering = ['grammatical_word']

    def __str__(self):
        return self.grammatical_word


class GrammatikManoData(models.Model):
    grammatik_manosi = models.TextField(verbose_name="So'zning grammatik ma'nosi")
    badiiy_uslub = models.TextField(verbose_name="Badiiy uslub", blank=True)
    ilmiy_uslub = models.TextField(verbose_name="Ilmiy uslub", blank=True)
    publitsistik_uslub = models.TextField(verbose_name="Publitsistik uslub", blank=True)
    rasmiy_uslub = models.TextField(verbose_name="Rasmiy uslub", blank=True)
    sozlashuv_uslubi = models.TextField(verbose_name="So'zlashuv uslubi", blank=True)

    class Meta:
        verbose_name = "Grammatik ma'no bo'yicha ma'lumot"
        verbose_name_plural = "Grammatik ma'no bo'yicha ma'lumotlar"
        ordering = ['grammatik_manosi']

    def __str__(self):
        return self.grammatik_manosi


class DavriylikiData(models.Model):
    period_11_12 = models.CharField(max_length=255, verbose_name="XI-XII asr", blank=True)
    period_13_14 = models.CharField(max_length=255, verbose_name="XIII-XIV asr", blank=True)
    period_15_18 = models.CharField(max_length=255, verbose_name="XV-XVIII asr", blank=True)
    period_19 = models.CharField(max_length=255, verbose_name="XIX asr", blank=True)
    period_20 = models.CharField(max_length=255, verbose_name="XX asr", blank=True)
    
    class Meta:
        verbose_name = "So'z davriyligi"
        verbose_name_plural = "So'z davriyligiga ko'ra"
    
    def __str__(self):
        return f"Davr: {self.period_11_12} - {self.period_20}"


class Sinonimlar(models.Model):
    grammatik_manosi = models.TextField(verbose_name="So'zning grammatik ma'nosi")
    sinonimlar = models.TextField(verbose_name="Sinonimlar")
    misol = models.TextField(verbose_name="Misol", blank=True)
    english = models.TextField(verbose_name="In English", blank=True)
    
    class Meta:
        verbose_name = "Sinonim"
        verbose_name_plural = "Sinonimlar"
        ordering = ['grammatik_manosi']
    
    def __str__(self):
        return self.grammatik_manosi

grammar_app/views.py
# This file is deprecated - please use the views package instead
# It's kept for backward compatibility during the transition

# Import all views from their respective modules
from .views.base_views import home, about, HomeView
from .views.category_views import CategoryDetailView, FormDetailView, export_category
from .views.search_views import SearchResultsView
from .views.yordamchi_views import YordamchiSozView, UmumiyBazaView, import_yordamchi_excel
from .views.sinonimlar_views import SinonimlarView, import_sinonimlar_excel
from .views.uslub_views import UslubView
from .views.word_synonym_views import WordSynonymView
from .views.grammatik_mano_views import GrammatikManoView, import_grammatik_excel
from .views.davriylik_views import DavriylikiView, import_davriylik_excel

# Re-export all the views
__all__ = [
    'home', 'about', 'HomeView',
    'CategoryDetailView', 'FormDetailView', 'export_category',
    'SearchResultsView',
    'YordamchiSozView', 'UmumiyBazaView', 'import_yordamchi_excel',
    'SinonimlarView', 'import_sinonimlar_excel',
    'UslubView',
    'WordSynonymView',
    'GrammatikManoView', 'import_grammatik_excel',
    'DavriylikiView', 'import_davriylik_excel',
]

grammar_app/views/base_views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from ..models import GrammaticalCategory


def home(request):
    categories = GrammaticalCategory.objects.all()
    # Get a few examples from each category for the homepage
    category_examples = {}
    for category in categories:
        category_examples[category] = category.forms.all()[:5]

    context = {
        'categories': categories,
        'category_examples': category_examples,
    }
    return render(request, 'grammar_app/home.html', context)


def about(request):
    return render(request, 'grammar_app/about.html')


class HomeView(TemplateView):
    template_name = 'grammar_app/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = GrammaticalCategory.objects.all()
        
        # Get examples from each category
        category_examples = {}
        for category in categories:
            category_examples[category] = category.forms.all()[:5]  # Get up to 5 recent forms

        context.update({
            'categories': categories,
            'category_examples': category_examples,
        })
        return context 

grammar_app/views/davriylik_views.py
from django.db.models import Q
from django.views.generic import ListView
from django.http import HttpResponse, JsonResponse
import pandas as pd
import json
from ..models import DavriylikiData


class DavriylikiView(ListView):
    model = DavriylikiData
    template_name = 'grammar_app/davriylik.html'
    context_object_name = 'items'
    paginate_by = 70  # Show 70 items per page

    def get_queryset(self):
        queryset = super().get_queryset()
        # Add search functionality
        q = self.request.GET.get('q')
        if q:
            queryset = queryset.filter(
                Q(period_11_12__icontains=q) |
                Q(period_13_14__icontains=q) |
                Q(period_15_18__icontains=q) |
                Q(period_19__icontains=q) |
                Q(period_20__icontains=q)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add total count to context
        context['total_items'] = self.model.objects.count()
        # Add current page number
        context['current_page'] = self.request.GET.get('page', 1)
        # Add search query if exists
        context['search_query'] = self.request.GET.get('q', '')
        return context

    def get(self, request, *args, **kwargs):
        if 'format' in request.GET:
            format_type = request.GET.get('format')
            queryset = self.get_queryset()
            
            if format_type == 'excel':
                return self.export_excel(queryset)
            elif format_type == 'json':
                return self.export_json(queryset)
        
        return super().get(request, *args, **kwargs)

    def export_excel(self, queryset):
        data = []
        for item in queryset:
            data.append({
                "XI-XII asrlar": item.period_11_12,
                "XIII-XIV asrlar": item.period_13_14,
                "XV-XVIII asrlar": item.period_15_18,
                "XIX asr": item.period_19,
                "XX asr": item.period_20,
            })
        
        df = pd.DataFrame(data)
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename="davriylik_data.xlsx"'
        df.to_excel(response, index=False)
        return response

    def export_json(self, queryset):
        data = []
        for item in queryset:
            data.append({
                "period_11_12": item.period_11_12,
                "period_13_14": item.period_13_14,
                "period_15_18": item.period_15_18,
                "period_19": item.period_19,
                "period_20": item.period_20,
            })
        
        response = HttpResponse(content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="davriylik_data.json"'
        json.dump(data, response, ensure_ascii=False, indent=2)
        return response


def import_davriylik_excel(request):
    try:
        # Read the Excel file
        df = pd.read_excel(r"C:\Users\Sanjar\Desktop\davriyligi.xlsx")
        
        # Print column names for debugging
        print("Available columns:", df.columns.tolist())
        print(f"Found {len(df)} rows in the Excel file")
        
        # Clear existing data if needed
        # DavriylikiData.objects.all().delete()
        
        # Track success and failures
        success_count = 0
        error_records = []
        
        # Process each row in the Excel file
        for index, row in df.iterrows():
            try:
                # Create a new record directly with period fields
                obj = DavriylikiData.objects.create(
                    period_11_12=row.get('XI-XII', '') if not pd.isna(row.get('XI-XII', '')) else '',
                    period_13_14=row.get('XIII-XIV', '') if not pd.isna(row.get('XIII-XIV', '')) else '',
                    period_15_18=row.get('XV-XVIII', '') if not pd.isna(row.get('XV-XVIII', '')) else '',
                    period_19=row.get('XIX', '') if not pd.isna(row.get('XIX', '')) else '',
                    period_20=row.get('XX', '') if not pd.isna(row.get('XX', '')) else '',
                )
                success_count += 1
                
            except Exception as e:
                error_records.append(f"Error in row {index+2}: {str(e)}")
                print(f"Error processing row {index+2}: {str(e)}")
        
        print(f"Successfully imported {success_count} items")
        if error_records:
            print(f"Encountered {len(error_records)} errors")
            
        return JsonResponse({
            'status': 'success', 
            'message': f'Data imported successfully. {success_count} records processed.', 
            'errors': error_records
        })
        
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}) 

grammar_app/views/uslub_views.py
from django.views.generic import ListView
from django.http import HttpResponse, JsonResponse
import pandas as pd
import json
from ..models import UslubData


class UslubView(ListView):
    model = UslubData
    template_name = 'grammar_app/uslub.html'
    context_object_name = 'items'

    def get(self, request, *args, **kwargs):
        if 'format' in request.GET:
            format_type = request.GET.get('format')
            queryset = self.get_queryset()
            
            if format_type == 'excel':
                return self.export_excel(queryset)
            elif format_type == 'json':
                return self.export_json(queryset)
        
        return super().get(request, *args, **kwargs)

    def export_excel(self, queryset):
        data = []
        for item in queryset:
            data.append({
                "Yordamchi so'z": item.yordamchi_soz,
                "Maxsus kodi": item.maxsus_kodi,
                "Grammatik ma'nosi": item.grammatik_manosi,
                "Badiiy": 1 if item.badiiy else 0,
                "Ilmiy": 1 if item.ilmiy else 0,
                "Publitsistik": 1 if item.publitsistik else 0,
                "Rasmiy": 1 if item.rasmiy else 0,
                "So'zlashuv": 1 if item.sozlashuv else 0,
            })
        
        df = pd.DataFrame(data)
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename="uslub_data.xlsx"'
        df.to_excel(response, index=False)
        return response

    def export_json(self, queryset):
        data = []
        for item in queryset:
            data.append({
                "yordamchi_soz": item.yordamchi_soz,
                "maxsus_kodi": item.maxsus_kodi,
                "grammatik_manosi": item.grammatik_manosi,
                "badiiy": item.badiiy,
                "ilmiy": item.ilmiy,
                "publitsistik": item.publitsistik,
                "rasmiy": item.rasmiy,
                "sozlashuv": item.sozlashuv,
            })
        
        response = HttpResponse(content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="uslub_data.json"'
        json.dump(data, response, ensure_ascii=False, indent=2)
        return response 

grammar_app/templates/grammar_app/davriylik.html
{% extends 'grammar_app/base.html' %}
{% load static %}

{% block title %}So'z davriyligiga ko'ra - Yordamchi so'zlar{% endblock %}

{% block content %}
<div class="container-fluid py-4">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Bosh sahifa</a></li>
            <li class="breadcrumb-item"><a href="{% url 'yordamchi_soz' %}">Yordamchi so'z</a></li>
            <li class="breadcrumb-item active">So'z davriyligiga ko'ra</li>
        </ol>
    </nav>

    <div class="row mb-4">
        <div class="col-md-6">
            <h1 class="mb-4">So'z davriyligiga ko'ra</h1>
        </div>
        <div class="col-md-6 text-md-end">
            <!-- Export buttons -->
            <a href="?format=excel{% if search_query %}&q={{ search_query }}{% endif %}" class="btn btn-success">
                <i class="bi bi-file-earmark-excel"></i> Excel formatida yuklash
            </a>
            <a href="?format=json{% if search_query %}&q={{ search_query }}{% endif %}" class="btn btn-primary ms-2">
                <i class="bi bi-file-earmark-code"></i> JSON formatida yuklash
            </a>
        </div>
    </div>

    <!-- Search form -->
    <div class="row mb-4">
        <div class="col-md-6 mx-auto">
            <form method="get" action="" class="d-flex">
                <input type="text" name="q" class="form-control" placeholder="Qidirish..." value="{{ search_query }}">
                <button type="submit" class="btn btn-primary ms-2">Qidirish</button>
                {% if search_query %}
                <a href="{% url 'davriylik' %}" class="btn btn-outline-secondary ms-2">Tozalash</a>
                {% endif %}
            </form>
        </div>
    </div>

    <!-- Data table -->
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>XI-XII asrlar</th>
                    <th>XIII-XIV asrlar</th>
                    <th>XV-XVIII asrlar</th>
                    <th>XIX asr</th>
                    <th>XX asr</th>
                </tr>
            </thead>
            <tbody>
                {% if items %}
                    {% for item in items %}
                    <tr>
                        <td>{{ item.period_11_12 }}</td>
                        <td>{{ item.period_13_14 }}</td>
                        <td>{{ item.period_15_18 }}</td>
                        <td>{{ item.period_19 }}</td>
                        <td>{{ item.period_20 }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center">Ma'lumot topilmadi</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <!-- Pagination -->
    {% if is_paginated %}
    <div class="d-flex justify-content-between align-items-center mt-4">
        <div>
            Jami: {{ total_items }} ta
            {% if total_items > 0 %}
                • Ko'rsatilyapti: {{ page_obj.start_index }}-{{ page_obj.end_index }}
            {% endif %}
        </div>
        
        <nav aria-label="Sahifalar">
            <ul class="pagination mb-0">
                <!-- First page -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <!-- Previous -->
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                
                <!-- Page numbers -->
                {% for num in paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}{% if search_query %}&q={{ search_query }}{% endif %}">{{ num }}</a></li>
                    {% elif num == page_obj.number|add:'-3' or num == page_obj.number|add:'3' %}
                        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                    {% endif %}
                {% endfor %}
                
                <!-- Next -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <!-- Last page -->
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginator.num_pages }}{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% endif %}
</div>

<style>
    /* Ensure the table headers stay fixed when scrolling horizontally */
    .table-responsive {
        overflow-x: auto;
    }
    
    /* Make first column sticky for easier reference */
    .table th:first-child,
    .table td:first-child {
        position: sticky;
        left: 0;
        z-index: 1;
        border-right: 2px solid #dee2e6;
    }
    
    /* Ensure all header cells have dark background */
    .table thead.table-dark th {
        background-color: #212529 !important;
        color: white !important;
        font-weight: 500;
    }
    
    /* First column header should match other headers */
    .table th:first-child {
        background-color: #212529;
    }
    
    /* First column data cells keep white background */
    .table td:first-child {
        background-color: #fff;
    }
    
    /* Add more visual separation between cells */
    .table td, .table th {
        padding: 0.75rem;
        vertical-align: top;
    }
    
    /* Highlight rows on hover */
    .table-hover tbody tr:hover {
        background-color: rgba(0, 123, 255, 0.05);
    }
    
    /* Mobile responsive adjustments */
    @media (max-width: 768px) {
        .pagination {
            flex-wrap: wrap;
            justify-content: center;
        }
    }
</style>
{% endblock %} 

grammar_app/templates/grammar_app/umumiy_baza.html
{% extends 'grammar_app/base.html' %}

{% block title %}Umumiy baza - Yordamchi so'zlar{% endblock %}

{% block content %}
<div class="container-fluid py-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Bosh sahifa</a></li>
            <li class="breadcrumb-item"><a href="{% url 'yordamchi_soz' %}">Yordamchi so'z</a></li>
            <li class="breadcrumb-item active">Umumiy baza</li>
        </ol>
    </nav>

    <div class="row mb-4">
        <div class="col-md-6">
            <h1 class="mb-4">Yordamchi so'zlar</h1>
        </div>
        <div class="col-md-6 text-md-end">
            <div class="btn-group">
                <a href="{% url 'export_category' category.id 'excel' %}" class="btn btn-success">
                    <i class="bi bi-file-earmark-excel"></i> Excel formatida yuklash
                </a>
                <a href="{% url 'export_category' category.id 'json' %}" class="btn btn-primary ms-2">
                    <i class="bi bi-file-earmark-code"></i> JSON formatida yuklash
                </a>
            </div>
        </div>
    </div>

    <div class="mb-4">
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-outline-primary active" data-filter="all">Hammasi</button>
            <button type="button" class="btn btn-outline-primary" data-filter="Ko'makchi">Ko'makchi</button>
            <button type="button" class="btn btn-outline-primary" data-filter="Bog'lovchi">Bog'lovchi</button>
            <button type="button" class="btn btn-outline-primary" data-filter="Yuklama">Yuklama</button>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Yordamchi so'z</th>
                    <th>Turkumi</th>
                    <th>Grammatik ma'nosi</th>
                    <th>Misollar</th>
                    <th>In English</th>
                    <th>Examples</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for form in forms %}
                <tr data-turkumi="{{ form.usage }}">
                    <td><strong>{{ form.term }}</strong></td>
                    <td>{{ form.get_usage_display }}</td>
                    <td>{{ form.grammatical_meaning }}</td>
                    <td>{{ form.examples.first.uzbek_text|default:"-" }}</td>
                    <td>{{ form.translation }}</td>
                    <td>{{ form.examples.first.english_translation|default:"-" }}</td>
                    <td>
                        <a href="{% url 'form_detail' form.pk %}" class="btn btn-sm btn-outline-primary rounded-pill">
                            <i class="fas fa-eye"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="7" class="text-center">Ma'lumotlar mavjud emas</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const filterButtons = document.querySelectorAll('[data-filter]');
    const rows = document.querySelectorAll('tbody tr[data-turkumi]');

    filterButtons.forEach(button => {
        button.addEventListener('click', function() {
            const filter = this.dataset.filter;
            
            filterButtons.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');

            rows.forEach(row => {
                if (filter === 'all' || row.dataset.turkumi === filter) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    });
});
</script>

<style>
    /* Button group styling */
    .btn-group .btn.active {
        background-color: #0d6efd;
        color: white;
    }

    /* Ensure the table headers stay fixed when scrolling horizontally */
    .table-responsive {
        overflow-x: auto;
    }
    
    /* Make first column sticky for easier reference */
    .table th:first-child,
    .table td:first-child {
        position: sticky;
        left: 0;
        z-index: 1;
        border-right: 2px solid #dee2e6;
    }
    
    /* Ensure all header cells have dark background */
    .table thead.table-dark th {
        background-color: #212529 !important;
        color: white !important;
        font-weight: 500;
    }
    
    /* First column header should match other headers */
    .table th:first-child {
        background-color: #212529;
    }
    
    /* First column data cells keep white background */
    .table td:first-child {
        background-color: #fff;
    }
    
    /* Add more visual separation between cells */
    .table td, .table th {
        padding: 0.75rem;
        vertical-align: top;
    }
    
    /* Highlight rows on hover */
    .table-hover tbody tr:hover {
        background-color: rgba(0, 123, 255, 0.05);
    }
    
    /* Mobile responsive adjustments */
    @media (max-width: 768px) {
        .pagination {
            flex-wrap: wrap;
            justify-content: center;
        }
    }
</style>
{% endblock %} 